[package]
name = "spin_future"
version = "0.1.0"
authors = ["paulkernfeld <me@paulkernfeld.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
futures-lite = "1.4.0"
